## Exploring Plotly library: 
Plotly's Python graphing library makes interactive, publication-quality graphs online. Examples of how to make line plots, scatter plots, area charts, bar charts, error bars, box plots, histograms, heatmaps, subplots, multiple-axes, polar charts, and bubble charts.

In [1]:
!pip install plotly==3.10.0

Requirement already satisfied: plotly==3.10.0 in /Users/faizan/opt/anaconda3/lib/python3.7/site-packages (3.10.0)
Requirement already satisfied: retrying>=1.3.3 in /Users/faizan/opt/anaconda3/lib/python3.7/site-packages (from plotly==3.10.0) (1.3.3)
Requirement already satisfied: nbformat>=4.2 in /Users/faizan/opt/anaconda3/lib/python3.7/site-packages (from plotly==3.10.0) (5.0.4)
Requirement already satisfied: six in /Users/faizan/opt/anaconda3/lib/python3.7/site-packages (from plotly==3.10.0) (1.14.0)
Requirement already satisfied: decorator>=4.0.6 in /Users/faizan/opt/anaconda3/lib/python3.7/site-packages (from plotly==3.10.0) (4.4.1)
Requirement already satisfied: pytz in /Users/faizan/opt/anaconda3/lib/python3.7/site-packages (from plotly==3.10.0) (2019.3)
Requirement already satisfied: requests in /Users/faizan/opt/anaconda3/lib/python3.7/site-packages (from plotly==3.10.0) (2.22.0)
Requirement already satisfied: traitlets>=4.1 in /Users/faizan/opt/anaconda3/lib/python3.7/site-packages (from nbformat>=4.2->plotly==3.10.0) (4.3.3)
Requirement already satisfied: jsonschema!=2.5.0,>=2.4 in /Users/faizan/opt/anaconda3/lib/python3.7/site-packages (from nbformat>=4.2->plotly==3.10.0) (3.2.0)
Requirement already satisfied: ipython-genutils in /Users/faizan/opt/anaconda3/lib/python3.7/site-packages (from nbformat>=4.2->plotly==3.10.0) (0.2.0)
Requirement already satisfied: jupyter-core in /Users/faizan/opt/anaconda3/lib/python3.7/site-packages (from nbformat>=4.2->plotly==3.10.0) (4.6.1)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /Users/faizan/opt/anaconda3/lib/python3.7/site-packages (from requests->plotly==3.10.0) (1.25.8)
Requirement already satisfied: idna<2.9,>=2.5 in /Users/faizan/opt/anaconda3/lib/python3.7/site-packages (from requests->plotly==3.10.0) (2.8)
Requirement already satisfied: certifi>=2017.4.17 in /Users/faizan/opt/anaconda3/lib/python3.7/site-packages (from requests->plotly==3.10.0) (2019.11.28)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in /Users/faizan/opt/anaconda3/lib/python3.7/site-packages (from requests->plotly==3.10.0) (3.0.4)
Requirement already satisfied: pyrsistent>=0.14.0 in /Users/faizan/opt/anaconda3/lib/python3.7/site-packages (from jsonschema!=2.5.0,>=2.4->nbformat>=4.2->plotly==3.10.0) (0.15.7)
Requirement already satisfied: setuptools in /Users/faizan/opt/anaconda3/lib/python3.7/site-packages (from jsonschema!=2.5.0,>=2.4->nbformat>=4.2->plotly==3.10.0) (46.0.0.post20200309)
Requirement already satisfied: importlib-metadata; python_version < "3.8" in /Users/faizan/opt/anaconda3/lib/python3.7/site-packages (from jsonschema!=2.5.0,>=2.4->nbformat>=4.2->plotly==3.10.0) (1.5.0)
Requirement already satisfied: attrs>=17.4.0 in /Users/faizan/opt/anaconda3/lib/python3.7/site-packages (from jsonschema!=2.5.0,>=2.4->nbformat>=4.2->plotly==3.10.0) (19.3.0)
Requirement already satisfied: zipp>=0.5 in /Users/faizan/opt/anaconda3/lib/python3.7/site-packages (from importlib-metadata; python_version < "3.8"->jsonschema!=2.5.0,>=2.4->nbformat>=4.2->plotly==3.10.0) (2.2.0)

In [2]:
!pip install cufflinks plotly
from plotly.offline import iplot, init_notebook_mode
import cufflinks
cufflinks.go_offline(connected=True)
init_notebook_mode(connected=True)

Requirement already satisfied: cufflinks in /Users/faizan/opt/anaconda3/lib/python3.7/site-packages (0.17.3)
Requirement already satisfied: plotly in /Users/faizan/opt/anaconda3/lib/python3.7/site-packages (3.10.0)
Requirement already satisfied: ipython>=5.3.0 in /Users/faizan/opt/anaconda3/lib/python3.7/site-packages (from cufflinks) (7.12.0)
Requirement already satisfied: numpy>=1.9.2 in /Users/faizan/opt/anaconda3/lib/python3.7/site-packages (from cufflinks) (1.18.1)
Requirement already satisfied: six>=1.9.0 in /Users/faizan/opt/anaconda3/lib/python3.7/site-packages (from cufflinks) (1.14.0)
Requirement already satisfied: setuptools>=34.4.1 in /Users/faizan/opt/anaconda3/lib/python3.7/site-packages (from cufflinks) (46.0.0.post20200309)
Requirement already satisfied: pandas>=0.19.2 in /Users/faizan/opt/anaconda3/lib/python3.7/site-packages (from cufflinks) (1.0.1)
Requirement already satisfied: colorlover>=0.2.1 in /Users/faizan/opt/anaconda3/lib/python3.7/site-packages (from cufflinks) (0.3.0)
Requirement already satisfied: ipywidgets>=7.0.0 in /Users/faizan/opt/anaconda3/lib/python3.7/site-packages (from cufflinks) (7.5.1)
Requirement already satisfied: decorator>=4.0.6 in /Users/faizan/opt/anaconda3/lib/python3.7/site-packages (from plotly) (4.4.1)
Requirement already satisfied: pytz in /Users/faizan/opt/anaconda3/lib/python3.7/site-packages (from plotly) (2019.3)
Requirement already satisfied: retrying>=1.3.3 in /Users/faizan/opt/anaconda3/lib/python3.7/site-packages (from plotly) (1.3.3)
Requirement already satisfied: nbformat>=4.2 in /Users/faizan/opt/anaconda3/lib/python3.7/site-packages (from plotly) (5.0.4)
Requirement already satisfied: requests in /Users/faizan/opt/anaconda3/lib/python3.7/site-packages (from plotly) (2.22.0)
Requirement already satisfied: pygments in /Users/faizan/opt/anaconda3/lib/python3.7/site-packages (from ipython>=5.3.0->cufflinks) (2.5.2)
Requirement already satisfied: pickleshare in /Users/faizan/opt/anaconda3/lib/python3.7/site-packages (from ipython>=5.3.0->cufflinks) (0.7.5)
Requirement already satisfied: traitlets>=4.2 in /Users/faizan/opt/anaconda3/lib/python3.7/site-packages (from ipython>=5.3.0->cufflinks) (4.3.3)
Requirement already satisfied: backcall in /Users/faizan/opt/anaconda3/lib/python3.7/site-packages (from ipython>=5.3.0->cufflinks) (0.1.0)
Requirement already satisfied: appnope; sys_platform == "darwin" in /Users/faizan/opt/anaconda3/lib/python3.7/site-packages (from ipython>=5.3.0->cufflinks) (0.1.0)
Requirement already satisfied: jedi>=0.10 in /Users/faizan/opt/anaconda3/lib/python3.7/site-packages (from ipython>=5.3.0->cufflinks) (0.14.1)
Requirement already satisfied: prompt-toolkit!=3.0.0,!=3.0.1,<3.1.0,>=2.0.0 in /Users/faizan/opt/anaconda3/lib/python3.7/site-packages (from ipython>=5.3.0->cufflinks) (3.0.3)
Requirement already satisfied: pexpect; sys_platform != "win32" in /Users/faizan/opt/anaconda3/lib/python3.7/site-packages (from ipython>=5.3.0->cufflinks) (4.8.0)
Requirement already satisfied: python-dateutil>=2.6.1 in /Users/faizan/opt/anaconda3/lib/python3.7/site-packages (from pandas>=0.19.2->cufflinks) (2.8.1)
Requirement already satisfied: widgetsnbextension~=3.5.0 in /Users/faizan/opt/anaconda3/lib/python3.7/site-packages (from ipywidgets>=7.0.0->cufflinks) (3.5.1)
Requirement already satisfied: ipykernel>=4.5.1 in /Users/faizan/opt/anaconda3/lib/python3.7/site-packages (from ipywidgets>=7.0.0->cufflinks) (5.1.4)
Requirement already satisfied: jsonschema!=2.5.0,>=2.4 in /Users/faizan/opt/anaconda3/lib/python3.7/site-packages (from nbformat>=4.2->plotly) (3.2.0)
Requirement already satisfied: jupyter-core in /Users/faizan/opt/anaconda3/lib/python3.7/site-packages (from nbformat>=4.2->plotly) (4.6.1)
Requirement already satisfied: ipython-genutils in /Users/faizan/opt/anaconda3/lib/python3.7/site-packages (from nbformat>=4.2->plotly) (0.2.0)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in /Users/faizan/opt/anaconda3/lib/python3.7/site-packages (from requests->plotly) (3.0.4)
Requirement already satisfied: certifi>=2017.4.17 in /Users/faizan/opt/anaconda3/lib/python3.7/site-packages (from requests->plotly) (2019.11.28)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /Users/faizan/opt/anaconda3/lib/python3.7/site-packages (from requests->plotly) (1.25.8)
Requirement already satisfied: idna<2.9,>=2.5 in /Users/faizan/opt/anaconda3/lib/python3.7/site-packages (from requests->plotly) (2.8)
Requirement already satisfied: parso>=0.5.0 in /Users/faizan/opt/anaconda3/lib/python3.7/site-packages (from jedi>=0.10->ipython>=5.3.0->cufflinks) (0.5.2)
Requirement already satisfied: wcwidth in /Users/faizan/opt/anaconda3/lib/python3.7/site-packages (from prompt-toolkit!=3.0.0,!=3.0.1,<3.1.0,>=2.0.0->ipython>=5.3.0->cufflinks) (0.1.8)
Requirement already satisfied: ptyprocess>=0.5 in /Users/faizan/opt/anaconda3/lib/python3.7/site-packages (from pexpect; sys_platform != "win32"->ipython>=5.3.0->cufflinks) (0.6.0)
Requirement already satisfied: notebook>=4.4.1 in /Users/faizan/opt/anaconda3/lib/python3.7/site-packages (from widgetsnbextension~=3.5.0->ipywidgets>=7.0.0->cufflinks) (6.0.3)
Requirement already satisfied: jupyter-client in /Users/faizan/opt/anaconda3/lib/python3.7/site-packages (from ipykernel>=4.5.1->ipywidgets>=7.0.0->cufflinks) (5.3.4)
Requirement already satisfied: tornado>=4.2 in /Users/faizan/opt/anaconda3/lib/python3.7/site-packages (from ipykernel>=4.5.1->ipywidgets>=7.0.0->cufflinks) (6.0.3)
Requirement already satisfied: importlib-metadata; python_version < "3.8" in /Users/faizan/opt/anaconda3/lib/python3.7/site-packages (from jsonschema!=2.5.0,>=2.4->nbformat>=4.2->plotly) (1.5.0)
Requirement already satisfied: attrs>=17.4.0 in /Users/faizan/opt/anaconda3/lib/python3.7/site-packages (from jsonschema!=2.5.0,>=2.4->nbformat>=4.2->plotly) (19.3.0)
Requirement already satisfied: pyrsistent>=0.14.0 in /Users/faizan/opt/anaconda3/lib/python3.7/site-packages (from jsonschema!=2.5.0,>=2.4->nbformat>=4.2->plotly) (0.15.7)
Requirement already satisfied: terminado>=0.8.1 in /Users/faizan/opt/anaconda3/lib/python3.7/site-packages (from notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.0.0->cufflinks) (0.8.3)
Requirement already satisfied: prometheus-client in /Users/faizan/opt/anaconda3/lib/python3.7/site-packages (from notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.0.0->cufflinks) (0.7.1)
Requirement already satisfied: nbconvert in /Users/faizan/opt/anaconda3/lib/python3.7/site-packages (from notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.0.0->cufflinks) (5.6.1)
Requirement already satisfied: Send2Trash in /Users/faizan/opt/anaconda3/lib/python3.7/site-packages (from notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.0.0->cufflinks) (1.5.0)
Requirement already satisfied: jinja2 in /Users/faizan/opt/anaconda3/lib/python3.7/site-packages (from notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.0.0->cufflinks) (2.11.1)
Requirement already satisfied: pyzmq>=17 in /Users/faizan/opt/anaconda3/lib/python3.7/site-packages (from notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.0.0->cufflinks) (18.1.1)
Requirement already satisfied: zipp>=0.5 in /Users/faizan/opt/anaconda3/lib/python3.7/site-packages (from importlib-metadata; python_version < "3.8"->jsonschema!=2.5.0,>=2.4->nbformat>=4.2->plotly) (2.2.0)
Requirement already satisfied: bleach in /Users/faizan/opt/anaconda3/lib/python3.7/site-packages (from nbconvert->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.0.0->cufflinks) (3.1.0)
Requirement already satisfied: defusedxml in /Users/faizan/opt/anaconda3/lib/python3.7/site-packages (from nbconvert->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.0.0->cufflinks) (0.6.0)
Requirement already satisfied: entrypoints>=0.2.2 in /Users/faizan/opt/anaconda3/lib/python3.7/site-packages (from nbconvert->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.0.0->cufflinks) (0.3)
Requirement already satisfied: testpath in /Users/faizan/opt/anaconda3/lib/python3.7/site-packages (from nbconvert->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.0.0->cufflinks) (0.4.4)
Requirement already satisfied: mistune<2,>=0.8.1 in /Users/faizan/opt/anaconda3/lib/python3.7/site-packages (from nbconvert->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.0.0->cufflinks) (0.8.4)
Requirement already satisfied: pandocfilters>=1.4.1 in /Users/faizan/opt/anaconda3/lib/python3.7/site-packages (from nbconvert->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.0.0->cufflinks) (1.4.2)
Requirement already satisfied: MarkupSafe>=0.23 in /Users/faizan/opt/anaconda3/lib/python3.7/site-packages (from jinja2->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.0.0->cufflinks) (1.1.1)
Requirement already satisfied: webencodings in /Users/faizan/opt/anaconda3/lib/python3.7/site-packages (from bleach->nbconvert->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.0.0->cufflinks) (0.5.1)

In [3]:
import pandas as pd
#import graph objects as "go"
import plotly.graph_objs as go

In [4]:
#Load data that we will use.
timesData = pd.read_csv("timesData.csv")

In [5]:
timesData.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2603 entries, 0 to 2602
Data columns (total 14 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   world_rank              2603 non-null   object
 1   university_name         2603 non-null   object
 2   country                 2603 non-null   object
 3   teaching                2603 non-null   float64
 4   international           2603 non-null   object
 5   research                2603 non-null   float64
 6   citations               2603 non-null   float64
 7   income                  2603 non-null   object
 8   total_score             2603 non-null   object
 9   num_students            2544 non-null   object
 10  student_staff_ratio     2544 non-null   float64
 11  international_students  2536 non-null   object
 12  female_male_ratio       2370 non-null   object
 13  year                    2603 non-null   int64
dtypes: float64(4), int64(1), object(9)
memory usage: 284.8+ KB

In [6]:
timesData.head()

,world_rank,university_name,country,teaching,international,research,citations,income,total_score,num_students,student_staff_ratio,international_students,female_male_ratio,year
0,1,Harvard University,United States of America,99.7,72.4,98.7,98.8,34.5,96.1,"20,152",8.9,25%,NaN,2011
1,2,California Institute of Technology,United States of America,97.7,54.6,98.0,99.9,83.7,96.0,"2,243",6.9,27%,33 : 67,2011
2,3,Massachusetts Institute of Technology,United States of America,97.8,82.3,91.4,99.9,87.5,95.6,"11,074",9.0,33%,37 : 63,2011
3,4,Stanford University,United States of America,98.3,29.5,98.1,99.2,64.3,94.3,"15,596",7.8,22%,42 : 58,2011
4,5,Princeton University,United States of America,90.9,70.3,95.4,99.9,-,94.2,"7,929",8.4,27%,45 : 55,2011


### Line Charts
Line Charts Example: Citation and Teaching vs World Rank of Top 100 Universities

- Import graph_objs as go
- Creating traces
    - x = x axis
    - y = y axis
    - mode = type of plot like marker, line or line + markers
    - name = name of the plots
    - marker = marker is used with dictionary.
        - color = color of lines. It takes RGB (red, green, blue) and opacity (alpha)
    - text = The hover text (hover is curser)
- data = is a list that we add traces into it
- layout = it is dictionary.
    - title = title of layout
    - x axis = it is dictionary
        - title = label of x axis
        - ticklen = length of x axis ticks
        - zeroline = showing zero line or not
- fig = it includes data and layout
- iplot() = plots the figure(fig) that is created by data and layout

In [7]:
#prepare dataframe
df = timesData.iloc[:100,:]

In [8]:
#Creating trace1
trace1 = go.Scatter(
                x = df.world_rank,
                y = df.citations,
                mode = "lines",
                name = "citations",
                marker = dict(color = 'rgba(16, 112, 2, 0.8)'),
                text = df.university_name)

In [9]:
#Creating trace2
trace2 = go.Scatter(
                x = df.world_rank,
                y = df.teaching,
                mode = "lines+markers",
                name = "teaching",
                marker = dict(color='rgba(80, 26, 80, 0.8)'),
                text = df.university_name)

In [10]:
data = [trace1, trace2]
layout = dict(title = "Citation and Teaching vs World Rank of Top 100 Universities",
             xaxis = dict(title= 'World Rank', ticklen= 5, zeroline=False))
fig = dict(data = data, layout = layout)
iplot(fig)

## Scatter
Scatter Example: Citation vs world rank of top 100 universities with 2014, 2015 and 2016 years
    
- Import graph_objs as go
- Creating traces
    - x = x axis
    - y = y axis
    - mode = type of plot like marker, line or line + markers
    - name = name of the plots
    - marker = marker is used with dictionary.
        - color = color of lines. It takes RGB (red, green, blue) and opacity (alpha)
    - text = The hover text (hover is curser)
- data = is a list that we add traces into it
- layout = it is dictionary.
    - title = title of layout
    - x axis = it is dictionary
        - title = label of x axis
        - ticklen = length of x axis ticks
        - zeroline = showing zero line or not
    - y axis = it is dictionary and same with x axis
- fig = it includes data and layout
- iplot() = plots the figure(fig) that is created by data and layout

In [11]:
# prepare data frames
df2014 = timesData[timesData.year == 2014].iloc[:100,:]
df2015 = timesData[timesData.year == 2015].iloc[:100,:]
df2016 = timesData[timesData.year == 2016].iloc[:100,:]

In [12]:
# creating trace1
trace1 =go.Scatter(
                    x = df2014.world_rank,
                    y = df2014.citations,
                    mode = "markers",
                    name = "2014",
                    marker = dict(color = 'rgba(255, 128, 255, 0.8)'),
                    text= df2014.university_name)

In [13]:
# creating trace2
trace2 =go.Scatter(
                    x = df2015.world_rank,
                    y = df2015.citations,
                    mode = "markers",
                    name = "2015",
                    marker = dict(color = 'rgba(255, 128, 2, 0.8)'),
                    text= df2015.university_name)

In [14]:
# creating trace3
trace3 =go.Scatter(
                    x = df2016.world_rank,
                    y = df2016.citations,
                    mode = "markers",
                    name = "2016",
                    marker = dict(color = 'rgba(0, 255, 200, 0.8)'),
                    text= df2016.university_name)

In [15]:
data = [trace1, trace2, trace3]
layout = dict(title = 'Citation vs world rank of top 100 universities with 2014, 2015 and 2016 years',
              xaxis= dict(title= 'World Rank',ticklen= 5,zeroline= False),
              yaxis= dict(title= 'Citation',ticklen= 5,zeroline= False)
             )
fig = dict(data = data, layout = layout)
iplot(fig)

## Bar Charts
First Bar Charts Example: citations and teaching of top 3 universities in 2014 (style1)

- Import graph_objs as go
- Creating traces
    - x = x axis
    - y = y axis
    - mode = type of plot like marker, line or line + markers
    - name = name of the plots
    - marker = marker is used with dictionary.
        - color = color of lines. It takes RGB (red, green, blue) and opacity (alpha)
        - line = It is dictionary. line between bars
            - color = line color around bars
    - text = The hover text (hover is curser)
- data = is a list that we add traces into it
- layout = it is dictionary.
    - barmode = bar mode of bars like grouped
- fig = it includes data and layout
- iplot() = plots the figure(fig) that is created by data and layout

In [16]:
# prepare data frames
df2014 = timesData[timesData.year == 2014].iloc[:3,:]
df2014

,world_rank,university_name,country,teaching,international,research,citations,income,total_score,num_students,student_staff_ratio,international_students,female_male_ratio,year
1002,1,California Institute of Technology,United States of America,94.4,65.8,98.2,99.8,91.2,94.9,"2,243",6.9,27%,33 : 67,2014
1003,2,Harvard University,United States of America,95.3,66.2,98.5,99.1,40.6,93.9,"20,152",8.9,25%,NaN,2014
1004,2,University of Oxford,United Kingdom,89.0,90.2,98.5,95.4,90.3,93.9,"19,919",11.6,34%,46 : 54,2014

In [17]:
# prepare data frames
df2014 = timesData[timesData.year == 2014].iloc[:3,:]

In [18]:
# create trace1 
trace1 = go.Bar(
                x = df2014.university_name,
                y = df2014.citations,
                name = "citations",
                marker = dict(color = 'rgba(255, 174, 255, 0.5)',
                             line=dict(color='rgb(0,0,0)',width=1.5)),
                text = df2014.country)

In [19]:
# create trace2 
trace2 = go.Bar(
                x = df2014.university_name,
                y = df2014.teaching,
                name = "teaching",
                marker = dict(color = 'rgba(255, 255, 128, 0.5)',
                              line=dict(color='rgb(0,0,0)',width=1.5)),
                text = df2014.country)

In [20]:
data = [trace1, trace2]
layout = go.Layout(barmode = "group")
fig = go.Figure(data = data, layout = layout)
iplot(fig)

## Pie Charts
Pie Charts Example: Students rate of top 7 universities in 2016

- fig: create figures
    - data: plot type
        - values: values of plot
        - labels: labels of plot
        - name: name of plots
        - hoverinfo: information in hover
        - hole: hole width
        - type: plot type like pie
    - layout: layout of plot
        - title: title of layout
        - annotations: font, showarrow, text, x, y

In [21]:
# data preparation
df2016 = timesData[timesData.year == 2016].iloc[:7,:]
pie1 = df2016.num_students
pie1_list = [float(each.replace(',', '.')) for each in df2016.num_students]  # str(2,4) => str(2.4) = > float(2.4) = 2.4
labels = df2016.university_name

In [22]:
# figure
fig = {
  "data": [
    {
      "values": pie1_list,
      "labels": labels,
      "domain": {"x": [0, .5]},
      "name": "Number Of Students Rates",
      "hoverinfo":"label+percent+name",
      "hole": .3,
      "type": "pie"
    },],
  "layout": {
        "title":"Universities Number of Students rates",
        "annotations": [
            { "font": { "size": 20},
              "showarrow": False,
              "text": "Number of Students",
                "x": 0.20,
                "y": 1
            },
        ]
    }
}
iplot(fig)

## Bubble Charts

Bubble Charts Example: University world rank (first 20) vs teaching score with number of students(size) and international score (color) in 2016

- x = x axis
- y = y axis
- mode = markers(scatter)
- marker = marker properties
    - color = third dimension of plot. Internaltional score
    - size = fourth dimension of plot. Number of students
- text: university names

In [23]:
df2016.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 7 entries, 1803 to 1809
Data columns (total 14 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   world_rank              7 non-null      object
 1   university_name         7 non-null      object
 2   country                 7 non-null      object
 3   teaching                7 non-null      float64
 4   international           7 non-null      object
 5   research                7 non-null      float64
 6   citations               7 non-null      float64
 7   income                  7 non-null      object
 8   total_score             7 non-null      object
 9   num_students            7 non-null      object
 10  student_staff_ratio     7 non-null      float64
 11  international_students  7 non-null      object
 12  female_male_ratio       6 non-null      object
 13  year                    7 non-null      int64
dtypes: float64(4), int64(1), object(9)
memory usage: 840.0+ bytes

In [24]:
# data preparation
df2016 = timesData[timesData.year == 2016].iloc[:20,:]
num_students_size  = [float(each.replace(',', '.')) for each in df2016.num_students]
international_color = [float(each) for each in df2016.international]

In [25]:
data = [
    {
        'y': df2016.teaching,
        'x': df2016.world_rank,
        'mode': 'markers',
        'marker': {
            'color': international_color,
            'size': num_students_size,
            'showscale': True
        },
        "text" :  df2016.university_name    
    }
]
iplot(data)

## Histogram
Lets look at histogram of students-staff ratio in 2011 and 2012 years.

- trace1 = first histogram
    - x = x axis
    - y = y axis
    - opacity = opacity of histogram
    - name = name of legend
    - marker = color of histogram
- trace2 = second histogram
- layout = layout
    - barmode = mode of histogram like overlay. Also you can change it with stack

In [27]:
# prepare data
x2011 = timesData.student_staff_ratio[timesData.year == 2011]
x2012 = timesData.student_staff_ratio[timesData.year == 2012]

In [28]:
trace1 = go.Histogram(
    x=x2011,
    opacity=0.75,
    name = "2011",
    marker=dict(color='rgba(171, 50, 96, 0.6)'))

In [29]:
trace2 = go.Histogram(
    x=x2012,
    opacity=0.75,
    name = "2012",
    marker=dict(color='rgba(12, 50, 196, 0.6)'))

In [30]:
data = [trace1, trace2]
layout = go.Layout(barmode='overlay',
                   title=' students-staff ratio in 2011 and 2012',
                   xaxis=dict(title='students-staff ratio'),
                   yaxis=dict( title='Count'),
)
fig = go.Figure(data=data, layout=layout)
iplot(fig)